### PR TITLE
ip dhcp-client: dhcp-options can be removed with value ''

### LINKED ISSUE #148: api_modify: Some routes shows "changed" when they shouldn't
##### SUMMARY

Some routes (I currently experiencing this only in `ip dhcp-client`, but there can be more) show `changed`, when there actually no changes. For example when I executing the following task muliple times:
```yaml
- name: Set DHCP client
  community.routeros.api_modify:
    path: ip dhcp-client
    data:
      - interface: ether1
        add-default-route: True
        default-route-distance: 1
        disabled: false
        use-peer-dns: True
        use-peer-ntp: True
        dhcp-options: ""
```
it always shows `changed` status, when no actually changes are performed (it is visible when enabling verbose output and comparing old_data and new_data)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.routeros.api_modify`

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.routeros 2.5.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
- Control host:
   -  OS: Arch Linux
    - Python version: 3.10.9
- Mikrotik RouterOS 7.7

##### STEPS TO REPRODUCE

Run a playbook with the task that modifies `ip dhcp-client` path of Mikrotik router

```yaml 
- name: Set DHCP client
  community.routeros.api_modify:
    path: ip dhcp-client
    data:
      - interface: ether1
        add-default-route: True
        default-route-distance: 1
        disabled: false
        use-peer-dns: True
        use-peer-ntp: True
        dhcp-options: ""
```

##### EXPECTED RESULTS
The status of task should be `ok`, not `changed` when applying the same configuration

##### ACTUAL RESULTS

```paste below
PLAY RECAP *************
localhost                  : ok=0    changed=1
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #148.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
api_info
api_modify

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]
FWIW the changes seem reasonable and the code is good. I don't understand the implications to the collection functionality though.

**Comment by felixfontein** [comment]
@Igorgro would you mind testing this?

**Comment by felixfontein** [comment]
@therfert if you happen to have a bit of time to take a look at this, that would be appreciated :)

**Comment by Igorgro** [comment]
@felixfontein confirmed. I've installed collection from this PR and now ansible shows '[ok]' for this task

**Comment by therfert** [comment]
> @therfert if you happen to have a bit of time to take a look at this, that would be appreciated :)

@felixfontein sorry, it took me a while to go through the code. I was concerned about how it will affect the changes done in https://github.com/ansible-collections/community.routeros/pull/128 But it looks good. I don't see any issues and it works good.

**Comment by felixfontein** [comment]
@maxamillion @Igorgro @therfert thanks a lot for reviewing and testing this! :)

**Pull request merged**
