### PR TITLE
Change to_text for to_native

### PR DESCRIPTION
**Pull request by renatoalmeidaoliveira**
##### SUMMARY
Substitute to_text for to_native as:
https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#raising-errors

##### ISSUE TYPE
lack of compatibility of to_text module

### CODE REVIEW

**Comment by felixfontein** [comment]
The document you link is about plugins and not modules, but I think it is also true for modules.

recheck

(that should re-run the zuul tests. they seem to fail a lot recently.)

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
Meh, looks like something is broken with Zuul. Well, let's just ignore it :)

**Comment by felixfontein** [comment]
Ah, **now** it restarted.

**Review by felixfontein — APPROVED** [review]

**Comment by heuels** [comment]
@renatoalmeidaoliveira, thanks for the contribution!
@felixfontein, thanks for reviewing this!

**Pull request merged**
