### PR TITLE
Fixes #193: Add caps-man channel and caps-man manager interface

### LINKED ISSUE #193: Add "caps-man channel" and enable "caps-man manager interface" paths
##### SUMMARY
The paths **caps-man channel** and **caps-man manager interface** should be supported.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- api_info
- api_modify

##### ADDITIONAL INFORMATION
Currently the **caps-man channel** path is not present at all. The settings could be set via **caps-man configuration** but some folks keep it seperated.
The **caps-man manager interface** path is present but "disabled" (`unknown_mechanism=True`).

### PR DESCRIPTION
**Pull request by derdeagle**
Adding the caps-man channel path from scratch.
Activating the caps-man manager interface path.

##### SUMMARY
Fixes #193.

Adding the caps-man channel path from scratch.
Activating the caps-man manager interface path.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- api_info
- api_modify

##### ADDITIONAL INFORMATION
None.

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Sorry for taking so long, I was on vacation and had no access to a MikroTik router ;)

**Comment by felixfontein** [comment]
@derdeagle thanks!

**Comment by derdeagle** [comment]
Thank you very much! No problem at all, it's on a voluntary basis so any time spent is appreciated ;)
By the way do you see any chance that we talk about this project and how MikroTik adds new parameters etc.? I already worked (locally) on the next changes for BGP stuff. If so please tell me how I can reach you.

**Comment by felixfontein** [comment]
I'm usually on Matrix in #community:ansible.com and on Libera IRC in #ansible-community. Depending on what you want to discuss starting a new issue in this repository might also be a good place for such a discussion, that way other interested parties can more easily weight in as well.

**Pull request merged**
