### PR TITLE
Add support for '/routing bgp' paths

### PR DESCRIPTION
**Pull request by vint2k**
##### SUMMARY
Support API paths:
- /routing bgp peer
- /routing bgp network
- /routing bgp aggregate

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- api_info
- api_modify

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks again! This also needs a changelog fragment.

**Comment by felixfontein** [comment]
Also please note that this one now has a conflict.

**Comment by vint2k** [comment]
@felixfontein done

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@vint2k thanks!

**Pull request merged**
